---
# handlers file for roles/node_exporter
  - name: Restart and enable node_exporter
    ansible.builtin.systemd:
      daemon_reload: yes
      state: restarted
      name: node_exporter
      enabled: yes